#!/usr/bin/env python3
"""Generate cryptographic test vectors for BIP-353 Identity Binding (milestone 1).

All cryptographic values are derived from real OpenPGP operations and
deterministic CBOR — nothing is invented.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reference import cbor
from reference.constants import (
    KEY_DOMAIN,
    KEY_IDENTIFIER,
    KEY_PAYMENT_HASH,
    KEY_ROOT_FINGERPRINT,
    KEY_SEQUENCE,
    KEY_SIGNATURE,
    KEY_SIGNING_FINGERPRINT,
)
from reference.identity import (
    build_anchor_message,
    build_identity_document,
    build_payment_binding,
    build_signed_identity_document,
    identity_commitment,
    identity_signing_message,
    payment_hash,
    provisional_op_return_payload,
)
from reference.openpgp_util import (
    detach_sign,
    export_public_key,
    get_primary_and_signing,
    verify_detach_sign,
)


# Fixed test parameters (artificial identity — NOT a real person)
DOMAIN = "example.test"
IDENTIFIER = "alice@example.test"
# P2WPKH scriptPubKey for 20 zero-ish bytes (test only)
SCRIPT_PUBKEY = bytes.fromhex("00141111111111111111111111111111111111111111")
CREATED_AT = 1790427664  # aligns with key creation epoch used in fixtures
EXPIRES_AT = 1821963664  # ~1 year later
SEQUENCE = 1


def write_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n")


def generate_valid(gnupghome: Path, out_dir: Path) -> dict:
    # Keys must already exist in GNUPGHOME (generated by setup / gpg batch).
    from reference.openpgp_util import _run_gpg, parse_colon_listing

    proc = _run_gpg(
        ["--with-colons", "--with-fingerprint", "--with-subkey-fingerprint", "--list-keys"],
        gnupghome=gnupghome,
    )
    infos = parse_colon_listing(proc.stdout.decode())
    root, sign = get_primary_and_signing(infos)

    out_dir.mkdir(parents=True, exist_ok=True)
    export_public_key(gnupghome, root.fingerprint_hex, out_dir / "root.asc")
    # Signing cert is embedded in the same OpenPGP certificate transfer
    shutil.copy(out_dir / "root.asc", out_dir / "signing.asc")

    payment = build_payment_binding([("bitcoin", SCRIPT_PUBKEY)])
    pay_cbor = cbor.dumps(payment)
    pay_hash = payment_hash(payment)

    signed = build_signed_identity_document(
        domain=DOMAIN,
        identifier=IDENTIFIER,
        root_fingerprint=root.fingerprint,
        signing_fingerprint=sign.fingerprint,
        created_at=CREATED_AT,
        expires_at=EXPIRES_AT,
        payment_hash_value=pay_hash,
        sequence=SEQUENCE,
    )
    payload_cbor = cbor.dumps(signed)
    message = identity_signing_message(signed)

    signature = detach_sign(
        message,
        gnupghome=gnupghome,
        signing_fingerprint_hex=sign.fingerprint_hex,
    )

    # Sanity: signature must verify immediately
    assert verify_detach_sign(
        message, signature, gnupghome=gnupghome, expected_signer_fpr=sign.fingerprint
    ), "freshly generated signature failed verification"

    identity_doc = build_identity_document(signed, signature)
    identity_cbor = cbor.dumps(identity_doc)

    anchor = build_anchor_message(
        domain=DOMAIN,
        identifier=IDENTIFIER,
        root_fingerprint=root.fingerprint,
    )
    anchor_cbor = cbor.dumps(anchor)
    commitment = identity_commitment(anchor)
    op_return = provisional_op_return_payload(commitment)

    write_bytes(out_dir / "payment-binding.cbor", pay_cbor)
    write_bytes(out_dir / "identity-payload.cbor", payload_cbor)
    write_bytes(out_dir / "identity-signature.bin", signature)
    write_bytes(out_dir / "identity-document.cbor", identity_cbor)
    write_bytes(out_dir / "anchor-message.cbor", anchor_cbor)
    write_bytes(out_dir / "anchor-opreturn-provisional.bin", op_return)

    expected = {
        "domain": DOMAIN,
        "identifier": IDENTIFIER,
        "kroot_fingerprint": root.fingerprint_hex,
        "ksign_fingerprint": sign.fingerprint_hex,
        "openpgp_version": 4,
        "openpgp_note": (
            "GnuPG 2.4.8 generated OpenPGP v4 Ed25519 keys "
            "(20-byte fingerprints). v6 fingerprints were NOT simulated."
        ),
        "payment_hash": pay_hash.hex(),
        "identity_commitment": commitment.hex(),
        "identity_payload_cbor_hex": payload_cbor.hex(),
        "identity_document_cbor_hex": identity_cbor.hex(),
        "payment_binding_cbor_hex": pay_cbor.hex(),
        "anchor_message_cbor_hex": anchor_cbor.hex(),
        "op_return_provisional_hex": op_return.hex(),
        "signature_hex": signature.hex(),
        "signature_valid": True,
        "anchor_valid": True,
        "created_at": CREATED_AT,
        "expires_at": EXPIRES_AT,
        "sequence": SEQUENCE,
        "script_pubkey_hex": SCRIPT_PUBKEY.hex(),
        "verification_time": CREATED_AT + 3600,
        "domain_separators": {
            "identity": "BIP353-IDENTITY\\x00\\x01",
            "payment": "BIP353-IDENTITY/PAYMENT/v1",
            "anchor": "BIP353-IDENTITY/ANCHOR/v1",
        },
        "expected_failure": None,
    }
    write_json(out_dir / "expected.json", expected)
    return expected


def mutate_cbor_map(data: bytes, key: int, new_value) -> bytes:
    obj = cbor.loads(data)
    obj[key] = new_value
    return cbor.dumps(obj)


def copy_valid_base(valid_dir: Path, dest: Path) -> None:
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(valid_dir, dest)


def generate_invalid(valid_dir: Path, invalid_root: Path) -> None:
    """Produce invalid vectors by mutating the valid fixture.

    Signatures are intentionally NOT re-computed when document fields change,
    except where noted — that is the point of the attack vector.
    """
    cases: list[tuple[str, str, callable]] = []

    def wrong_domain(d: Path):
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_DOMAIN,
            "evil.example",
        )
        # Also break identifier consistency separately — here domain alone
        write_bytes(d / "identity-document.cbor", doc)
        # Update expected
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "DOMAIN_IDENTIFIER_INCONSISTENT"
        exp["signature_valid"] = False  # signature over original domain
        write_json(d / "expected.json", exp)

    def wrong_identifier(d: Path):
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_IDENTIFIER,
            "bob@example.test",
        )
        write_bytes(d / "identity-document.cbor", doc)
        exp = json.loads((d / "expected.json").read_text())
        exp["identifier"] = "alice@example.test"  # requested stays original
        exp["expected_failure"] = "IDENTIFIER_MISMATCH"
        write_json(d / "expected.json", exp)

    def wrong_root(d: Path):
        fake = bytes.fromhex("000102030405060708090a0b0c0d0e0f10111213")
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_ROOT_FINGERPRINT,
            fake,
        )
        write_bytes(d / "identity-document.cbor", doc)
        # Also mutate anchor so payment/sig paths aren't the only failure
        anchor = mutate_cbor_map(
            (d / "anchor-message.cbor").read_bytes(),
            3,  # ANCHOR_ROOT
            fake,
        )
        write_bytes(d / "anchor-message.cbor", anchor)
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "ROOT_KEY_MISMATCH"
        exp["identity_commitment"] = identity_commitment(
            build_anchor_message(
                domain=DOMAIN, identifier=IDENTIFIER, root_fingerprint=fake
            )
        ).hex()
        write_json(d / "expected.json", exp)

    def wrong_signing_key(d: Path):
        fake = bytes.fromhex("202122232425262728292a2b2c2d2e2f30313233")
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_SIGNING_FINGERPRINT,
            fake,
        )
        write_bytes(d / "identity-document.cbor", doc)
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "SIGNING_KEY_MISMATCH"
        write_json(d / "expected.json", exp)

    def invalid_signature(d: Path):
        doc = cbor.loads((d / "identity-document.cbor").read_bytes())
        sig = bytearray(doc[KEY_SIGNATURE])
        sig[20] ^= 0xFF
        doc[KEY_SIGNATURE] = bytes(sig)
        write_bytes(d / "identity-document.cbor", cbor.dumps(doc))
        write_bytes(d / "identity-signature.bin", bytes(sig))
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "INVALID_IDENTITY_SIGNATURE"
        exp["signature_valid"] = False
        write_json(d / "expected.json", exp)

    def expired(d: Path):
        exp = json.loads((d / "expected.json").read_text())
        # verification_time after expires_at
        exp["verification_time"] = exp["expires_at"] + 1
        exp["expected_failure"] = "IDENTITY_EXPIRED"
        write_json(d / "expected.json", exp)

    def wrong_payment(d: Path):
        # Different scriptPubKey → different payment binding, but identity
        # document still has old payment_hash
        new_script = bytes.fromhex("00142222222222222222222222222222222222222222")
        payment = build_payment_binding([("bitcoin", new_script)])
        write_bytes(d / "payment-binding.cbor", cbor.dumps(payment))
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "PAYMENT_BINDING_MISMATCH"
        write_json(d / "expected.json", exp)

    def wrong_payment_hash(d: Path):
        fake_hash = bytes(32)
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_PAYMENT_HASH,
            fake_hash,
        )
        write_bytes(d / "identity-document.cbor", doc)
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "INVALID_IDENTITY_SIGNATURE"
        # Note: signature fails first because payment_hash is in signed payload.
        # If signature somehow passed, payment binding would also fail.
        write_json(d / "expected.json", exp)

    def wrong_anchor(d: Path):
        fake_root = bytes.fromhex("ffffffffffffffffffffffffffffffffffffffff")
        anchor = build_anchor_message(
            domain=DOMAIN,
            identifier=IDENTIFIER,
            root_fingerprint=fake_root,
        )
        write_bytes(d / "anchor-message.cbor", cbor.dumps(anchor))
        exp = json.loads((d / "expected.json").read_text())
        # Document still has real root; anchor fields mismatch
        exp["expected_failure"] = "ANCHOR_MISMATCH"
        exp["identity_commitment"] = identity_commitment(anchor).hex()
        write_json(d / "expected.json", exp)

    def sequence_modified(d: Path):
        doc = mutate_cbor_map(
            (d / "identity-document.cbor").read_bytes(),
            KEY_SEQUENCE,
            999,
        )
        write_bytes(d / "identity-document.cbor", doc)
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = "INVALID_IDENTITY_SIGNATURE"
        exp["sequence"] = 999
        write_json(d / "expected.json", exp)

    def rollback(d: Path):
        """Illustrates freshness gap: an older but still-valid document.

        Document remains cryptographically valid; expected_failure is None for
        crypto checks, but freshness remains UNKNOWN. Documented in notes.
        """
        exp = json.loads((d / "expected.json").read_text())
        exp["expected_failure"] = None
        exp["notes"] = (
            "ROLLBACK DEMO: this vector is cryptographically valid. "
            "A compromised server can replay sequence=1 after sequence=2 was "
            "published. Stateless verification alone cannot detect this. "
            "Freshness requires a transparency log (V2)."
        )
        exp["freshness"] = "unknown"
        exp["rollback_undetectable_without_transparency"] = True
        write_json(d / "expected.json", exp)

    mutators = {
        "wrong-domain": wrong_domain,
        "wrong-identifier": wrong_identifier,
        "wrong-root": wrong_root,
        "wrong-signing-key": wrong_signing_key,
        "invalid-signature": invalid_signature,
        "expired": expired,
        "wrong-payment": wrong_payment,
        "wrong-payment-hash": wrong_payment_hash,
        "wrong-anchor": wrong_anchor,
        "sequence-modified": sequence_modified,
        "rollback": rollback,
    }

    for name, fn in mutators.items():
        dest = invalid_root / name
        copy_valid_base(valid_dir, dest)
        fn(dest)
        print(f"  generated invalid/{name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--gnupghome",
        type=Path,
        default=Path(os.environ.get("GNUPGHOME", "/tmp/bip353-gnupg")),
    )
    args = parser.parse_args()

    valid_dir = ROOT / "vectors" / "valid"
    invalid_dir = ROOT / "vectors" / "invalid"

    print(f"Using GNUPGHOME={args.gnupghome}")
    print("Generating valid vector...")
    expected = generate_valid(args.gnupghome, valid_dir)
    print(f"  KROOT={expected['kroot_fingerprint']}")
    print(f"  KSIGN={expected['ksign_fingerprint']}")
    print(f"  payment_hash={expected['payment_hash']}")
    print(f"  identity_commitment={expected['identity_commitment']}")

    print("Generating invalid vectors...")
    if invalid_dir.exists():
        shutil.rmtree(invalid_dir)
    invalid_dir.mkdir(parents=True)
    generate_invalid(valid_dir, invalid_dir)

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
